# Assignment - Numpy

-Create 4x4 array of all True values

-Create 4x4 array of all False values

-Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's

-Create 4x4 array of Digonal elements as True and Non diagonal elements as False

-Create 4x4 array of Digonal elements as False and Non diagonal elements as True

In [1]:
import numpy as np

In [3]:
# Create 4x4 array of all True values
x=np.full((4,4),'True')

In [4]:
x

array([['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True']], dtype='<U4')

In [5]:
x= np.ones((4, 4), dtype=bool)

In [6]:
x

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
#x= np.zeros((4, 4), dtype=bool)

In [ ]:
# Create 4x4 array of all False values

In [13]:
y= np.zeros((4, 4), dtype=bool)

In [14]:
y

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [15]:
y=np.full((4,4),'False')

In [16]:
y

array([['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False']], dtype='<U5')

In [17]:
#Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's

In [18]:
z = np.eye(4)
print(z)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
z = np.eye(4,dtype=bool)
print(z)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [21]:
z = np.eye(4,dtype=int)
print(z)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [22]:
# Create 4x4 array of Digonal elements as False and Non diagonal elements as True

In [23]:
a = np.eye(4, dtype=bool)
a = ~a
print(a)

[[False  True  True  True]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True False]]


In [24]:
a = ~np.eye(4, dtype=bool)

In [25]:
a

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])